apiVersion: v2

name: v2ray

description: A Helm charts for deploying V2Ray to Kubernetes.

type: application

version: 1.0.1

appVersion: V4.34.0

maintainers:
  - email: varroreve@gmail.com
    name: Varro Reve

home: https://github.com/VarroReve/v2ray-helm-charts

icon: https://www.v2fly.org/v2ray.png

sources:
  - https://github.com/VarroReve/v2ray-helm-charts

keywords:
  - v2ray
  - v2fly